# Generated by Django 2.1.7 on 2020-04-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='art_class',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
